-- ============================================================================
-- DATABASE EXPLORATION
-- DIMENSIONS OVERVIEW
-- Purpose: Understand available tables, columns, and dimensional attributes
-- ============================================================================

-- List all tables in the GOLD schema
SELECT *
FROM information_schema.tables
WHERE table_schema = 'gold';

-- Inspect columns of the customer dimension
SELECT *
FROM information_schema.columns
WHERE table_name = 'dim_customers'
ORDER BY ordinal_position;

-- Identify distinct countries of customers
SELECT DISTINCT country
FROM gold.dim_customers;

-- Explore product hierarchy: category → subcategory → product
SELECT DISTINCT
	category,
	subcategory,
	product_name
FROM gold.dim_products
ORDER BY 1, 2, 3;



-- ============================================================================
-- DATE EXPLORATION
-- Purpose: Understand data time coverage and customer age distribution
-- ============================================================================

-- Identify first and last order dates and overall time span
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	AGE(MAX(order_date), MIN(order_date)) AS data_time_span
FROM gold.fact_sales;

-- Identify youngest and oldest customers (age calculated from birthdate)
SELECT
	MIN(birthdate) AS oldest_customer_birthdate,
	EXTRACT(YEAR FROM AGE(NOW(), MIN(birthdate))) AS age_oldest_customer,
	MAX(birthdate) AS youngest_customer_birthdate,
	EXTRACT(YEAR FROM AGE(NOW(), MAX(birthdate))) AS age_youngest_customer
FROM gold.dim_customers;



-- ============================================================================
-- KEY BUSINESS METRICS
-- Purpose: High-level KPIs describing overall business performance
-- ============================================================================

-- Consolidated KPI table using UNION ALL
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity Sold', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', ROUND(AVG(price), 2) FROM gold.fact_sales
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers
UNION ALL
SELECT 'Active Customers (Placed Orders)', COUNT(DISTINCT customer_key) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(product_key) FROM gold.dim_products
UNION ALL
SELECT 'Products Sold', COUNT(DISTINCT product_key) FROM gold.fact_sales;



-- ============================================================================
-- CUSTOMER & PRODUCT DISTRIBUTIONS
-- Purpose: Understand customer and product composition
-- ============================================================================

-- Customer distribution by country
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Customer distribution by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Product count by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Average product cost by category
SELECT
	category,
	ROUND(AVG(cost), 2) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;



-- ============================================================================
-- REVENUE ANALYSIS
-- Purpose: Identify revenue drivers across categories and customers
-- ============================================================================

-- Total revenue generated per product category
SELECT
	pr.category,
	SUM(sl.sales_amount) AS total_revenue
FROM gold.fact_sales sl
LEFT JOIN gold.dim_products pr 
	ON sl.product_key = pr.product_key
GROUP BY pr.category
ORDER BY total_revenue DESC;

-- Total revenue generated by each customer
SELECT
	cu.customer_key,
	cu.first_name,
	cu.last_name,
	SUM(sl.sales_amount) AS total_revenue
FROM gold.fact_sales sl
LEFT JOIN gold.dim_customers cu 
	ON sl.customer_key = cu.customer_key
GROUP BY cu.customer_key, cu.first_name, cu.last_name
ORDER BY total_revenue DESC;

-- Distribution of sold quantities across countries and product categories
SELECT
	cu.country,
	pr.category,
	SUM(sl.quantity) AS total_sold_items
FROM gold.fact_sales sl
LEFT JOIN gold.dim_customers cu 
	ON sl.customer_key = cu.customer_key
LEFT JOIN gold.dim_products pr 
	ON sl.product_key = pr.product_key
GROUP BY cu.country, pr.category
ORDER BY cu.country, pr.category;



-- ============================================================================
-- TOP-N / BOTTOM-N ANALYSIS
-- Purpose: Identify best and worst performers
-- ============================================================================

-- Top 5 products by total revenue
SELECT
	pr.product_name,
	SUM(sl.sales_amount) AS total_revenue
FROM gold.fact_sales sl
LEFT JOIN gold.dim_products pr 
	ON sl.product_key = pr.product_key
GROUP BY pr.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- Bottom 5 products by total revenue (using ranking)
SELECT *
FROM (
	SELECT
		pr.product_name,
		SUM(sl.sales_amount) AS total_revenue,
		RANK() OVER (ORDER BY SUM(sl.sales_amount) ASC) AS product_rank
	FROM gold.fact_sales sl
	LEFT JOIN gold.dim_products pr 
		ON sl.product_key = pr.product_key
	GROUP BY pr.product_name
) t
WHERE product_rank <= 5;

-- Top 10 customers by total revenue
SELECT
	cu.customer_key,
	cu.first_name,
	cu.last_name,
	SUM(sl.sales_amount) AS total_revenue
FROM gold.fact_sales sl
LEFT JOIN gold.dim_customers cu 
	ON sl.customer_key = cu.customer_key
GROUP BY cu.customer_key, cu.first_name, cu.last_name
ORDER BY total_revenue DESC
LIMIT 10;

-- Customers who placed exactly one order
SELECT
	cu.customer_key,
	cu.first_name,
	cu.last_name,
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales sl
LEFT JOIN gold.dim_customers cu 
	ON sl.customer_key = cu.customer_key
GROUP BY cu.customer_key, cu.first_name, cu.last_name
HAVING COUNT(DISTINCT order_number) = 1;
